FROM rstudio/plumber

# Install pandoc
RUN apt-get update && apt-get install -y --no-install-recommends \
    pandoc \
    && rm -rf /var/lib/apt/lists/*

# Install additional packages
RUN R -q -e "install.packages(c('remotes', 'base4enc', 'rmarkdown', 'jsonlite', 'ggplot2'))"
RUN R -q -e "remotes::install_github('rileywheadon/ffa-framework')"

# Put Plumber file in a known location
WORKDIR /app
COPY plumber.R /app/plumber.R
EXPOSE 8000

# Run R Plumber
CMD ["/app/plumber.R"]

